# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/edwardwhitesel/Downloads/sfml_astroids-main 2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/edwardwhitesel/Downloads/sfml_astroids-main 2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/edwardwhitesel/Downloads/sfml_astroids-main 2/CMakeFiles" "/Users/edwardwhitesel/Downloads/sfml_astroids-main 2//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/edwardwhitesel/Downloads/sfml_astroids-main 2/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sfml_astroids

# Build rule for target.
sfml_astroids: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml_astroids
.PHONY : sfml_astroids

# fast build rule for target.
sfml_astroids/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/build
.PHONY : sfml_astroids/fast

Collision/Collider.o: Collision/Collider.cpp.o
.PHONY : Collision/Collider.o

# target to build an object file
Collision/Collider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Collision/Collider.cpp.o
.PHONY : Collision/Collider.cpp.o

Collision/Collider.i: Collision/Collider.cpp.i
.PHONY : Collision/Collider.i

# target to preprocess a source file
Collision/Collider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Collision/Collider.cpp.i
.PHONY : Collision/Collider.cpp.i

Collision/Collider.s: Collision/Collider.cpp.s
.PHONY : Collision/Collider.s

# target to generate assembly for a file
Collision/Collider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Collision/Collider.cpp.s
.PHONY : Collision/Collider.cpp.s

Entities/Astroid/Astroid.o: Entities/Astroid/Astroid.cpp.o
.PHONY : Entities/Astroid/Astroid.o

# target to build an object file
Entities/Astroid/Astroid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Entities/Astroid/Astroid.cpp.o
.PHONY : Entities/Astroid/Astroid.cpp.o

Entities/Astroid/Astroid.i: Entities/Astroid/Astroid.cpp.i
.PHONY : Entities/Astroid/Astroid.i

# target to preprocess a source file
Entities/Astroid/Astroid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Entities/Astroid/Astroid.cpp.i
.PHONY : Entities/Astroid/Astroid.cpp.i

Entities/Astroid/Astroid.s: Entities/Astroid/Astroid.cpp.s
.PHONY : Entities/Astroid/Astroid.s

# target to generate assembly for a file
Entities/Astroid/Astroid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Entities/Astroid/Astroid.cpp.s
.PHONY : Entities/Astroid/Astroid.cpp.s

Entities/Bullet/Bullet.o: Entities/Bullet/Bullet.cpp.o
.PHONY : Entities/Bullet/Bullet.o

# target to build an object file
Entities/Bullet/Bullet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Entities/Bullet/Bullet.cpp.o
.PHONY : Entities/Bullet/Bullet.cpp.o

Entities/Bullet/Bullet.i: Entities/Bullet/Bullet.cpp.i
.PHONY : Entities/Bullet/Bullet.i

# target to preprocess a source file
Entities/Bullet/Bullet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Entities/Bullet/Bullet.cpp.i
.PHONY : Entities/Bullet/Bullet.cpp.i

Entities/Bullet/Bullet.s: Entities/Bullet/Bullet.cpp.s
.PHONY : Entities/Bullet/Bullet.s

# target to generate assembly for a file
Entities/Bullet/Bullet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Entities/Bullet/Bullet.cpp.s
.PHONY : Entities/Bullet/Bullet.cpp.s

Entities/Object.o: Entities/Object.cpp.o
.PHONY : Entities/Object.o

# target to build an object file
Entities/Object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Entities/Object.cpp.o
.PHONY : Entities/Object.cpp.o

Entities/Object.i: Entities/Object.cpp.i
.PHONY : Entities/Object.i

# target to preprocess a source file
Entities/Object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Entities/Object.cpp.i
.PHONY : Entities/Object.cpp.i

Entities/Object.s: Entities/Object.cpp.s
.PHONY : Entities/Object.s

# target to generate assembly for a file
Entities/Object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Entities/Object.cpp.s
.PHONY : Entities/Object.cpp.s

Entities/Player/Player.o: Entities/Player/Player.cpp.o
.PHONY : Entities/Player/Player.o

# target to build an object file
Entities/Player/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Entities/Player/Player.cpp.o
.PHONY : Entities/Player/Player.cpp.o

Entities/Player/Player.i: Entities/Player/Player.cpp.i
.PHONY : Entities/Player/Player.i

# target to preprocess a source file
Entities/Player/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Entities/Player/Player.cpp.i
.PHONY : Entities/Player/Player.cpp.i

Entities/Player/Player.s: Entities/Player/Player.cpp.s
.PHONY : Entities/Player/Player.s

# target to generate assembly for a file
Entities/Player/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/Entities/Player/Player.cpp.s
.PHONY : Entities/Player/Player.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml_astroids.dir/build.make CMakeFiles/sfml_astroids.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sfml_astroids"
	@echo "... Collision/Collider.o"
	@echo "... Collision/Collider.i"
	@echo "... Collision/Collider.s"
	@echo "... Entities/Astroid/Astroid.o"
	@echo "... Entities/Astroid/Astroid.i"
	@echo "... Entities/Astroid/Astroid.s"
	@echo "... Entities/Bullet/Bullet.o"
	@echo "... Entities/Bullet/Bullet.i"
	@echo "... Entities/Bullet/Bullet.s"
	@echo "... Entities/Object.o"
	@echo "... Entities/Object.i"
	@echo "... Entities/Object.s"
	@echo "... Entities/Player/Player.o"
	@echo "... Entities/Player/Player.i"
	@echo "... Entities/Player/Player.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

